### ISSUE TITLE
About cuhk mail on GNOME Evolution

### ISSUE THREAD

**Issue by huhanwj** [han-storage/irregular-logs#4]
No exchange or similar option on my evolution client app? What is happening?
@Zhmjharmgal 
Can you provide a more detailed tutorial on this?

**Comment by Zhmjharmgal** [comment]
Try run this:
~~~
sudo apt install evolution evolution-ews
~~~
before restarting Evolution

**Comment by Zhmjharmgal** [comment]
Damn, this is way worse than just using web office365. It always fails to fetch letters, gets no-response errors, and seemingly requires vpn to work.

**Comment by huhanwj** [comment]
> 
> 
> Damn, this is way worse than just using web office365. It always fails to fetch letters, gets no-response errors, and seemingly requires vpn to work.

I see, it may depends on your network environment.
